#!/bin/bash -e
GITW_SYMLINK=$(readlink "$0")
if [ -n "$GITW_SYMLINK" ]
then
  GITW_SYMLINK_DIRECTORY=$(dirname "$GITW_SYMLINK")
  GITW_FILE_DIRECTORY=$(cd "$GITW_FILE_DIRECTORY" &&
                        cd "$GITW_SYMLINK_DIRECTORY" && pwd -P)
fi
export GITW_FILE_DIRECTORY
export PATH=$PATH:$GITW_FILE_DIRECTORY
source toolkit

GIT=`which git`
command=$2
### Wrapping p4 commands
if [ "$1" == "p4" ]; then
  case "$command" in
    "integ")
      shift 2
      check_p4_login || exit 1
      sh git-p4-integ "$@"
    ;;
    "labels")
      shift 2
      check_p4_login || exit 1
      sh git-p4-labels "$@"
    ;;
    "build")
      shift 2
      sh git-p4-build "$@"
    ;;

    *)
      check_p4_login || exit 1
      $GIT "$@"
    ;;
  esac
### Native git commands
else
  $GIT "$@"
fi
exit $?
