#!/bin/bash -e
pushd $(dirname $BASH_SOURCE[0]) > /dev/null
echo "Auto CI submitter"

if [ -z "$(which casperjs)" ];then
  echo "Please install casperjs. (try 'brew install casperjs --devel')"
  exit 1
fi

read -p "User: " user
read -s -p "Password:" pass
echo
echo "1) MUP_iOS_1.0_MAIN (mac10_8) [en, ja]"
echo "2) iTMMS_2.0_MAIN (mac10_8) [en, ja]"
read -p "Project Name:" project_index

case $project_index in
  1) project="MUP_iOS_1.0_MAIN" ;;
  2) project="iTMMS_2.0_MAIN";;
  *) echo "INVALID NUMBER!";exit 1 ;;
esac

read -p "Purpose:" purpose

casperjs git-p4-build.js --user=$user --pass=$pass --project=$project --purpose=$purpose
popd
